pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews
    conditions:
      - "#approved-reviews-by>=2"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - status-success=CI / check_submodules (pull_request)
      - status-success=CI / build (pull_request)
      - status-success=CI / precommit (pull_request)
      - status-success=CI / check_artemis (pull_request)
      - status-success=default
      - base=dev
      - label!=dot_not_merge
      - label!=wip
      - label!=waiting
      - label!=merge_after_release
      - author=@coreteam
    actions:
      merge:
        method: merge
        strict: smart   # To avoid multiple builds at once on the CI
        strict_method: rebase # We want Dev rebased onto the PR
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
