
language: cpp
sudo: required

services:
  - docker
  - rabbitmq

git:
  submodules: false

before_install:
  - sudo apt update && sudo apt install -y python-pip python-dev protobuf-compiler
  - sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
  - git submodule update --init --recursive
  - sudo pip install -r source/tyr/requirements_dev.txt
  - bash source/scripts/build_protobuf.sh

script:
  # Make sure submodules references are merged in !
  - bash source/scripts/check_submodules.sh
  - pushd source/tyr && PYTHONPATH=.:../navitiacommon/ py.test && popd
