
language: python
python:
  - "2.7"
  - "3.6"
sudo: required
cache: pip
dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-format-6.0
    - rabbitmq-server

services:
  - docker
  - rabbitmq
  - redis

git:
  submodules: false

before_install:
  - sudo apt update && sudo apt install -y protobuf-compiler
  - sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
  - git submodule update --init --recursive

before_script:
  - pip install -r source/tyr/requirements_dev.txt
  - pip install pre-commit
  - pre-commit install
  - bash source/scripts/build_protobuf.sh

script:
  # Make sure submodules references are merged in !
  - bash source/scripts/check_submodules.sh
  - pushd source && pre-commit run clang-format --all --show-diff-on-failure; popd
  - pushd source/tyr && PYTHONPATH=.:../navitiacommon/ py.test --doctest-modules --ignore=migrations/ ; popd

matrix:
  include:
    - python: "3.6"
      before_script:
        - python3.6 -m pip install black==18.9b0
        - pip install -r source/jormungandr/requirements_dev.txt
        - bash source/scripts/build_protobuf.sh
      script:
        - black --check --diff .
        - pushd source/jormungandr && MYPYPATH=.:../navitiacommon mypy --ignore-missing-imports --py2 jormungandr && popd
  exclude:
    - python: "3.6"
