name: Build Navitia Packages For Dev

on:
  push:
    branches:
      - dev


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: navitia/debian8_dev

    steps:
    - uses: actions/checkout@v1
    - name: install zip dependency
      run: apt update && apt install -y zip httpie
    - name: dkpg-buildpackage
      run: |
        sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        git submodule update --init --recursive
        DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b
    - name: create navitia_debian_packages.zip
      run: |
        zip navitia_debian_packages.zip ../navitia-*
    - name: upload debian packages
      uses: actions/upload-artifact@v1
      with:
        name: navitia-debian-packages
        path: "navitia_debian_packages.zip"
    - name: remove useless temporary files
      run: rm -rf ../navitia-*
    - name: trigger deploy on artemis
      run: http -v -f POST https://${{secrets.jenkins_token}}@ci.navitia.io/job/deploy_navitia_on_artemis_from_github/build
    - name: slack notification (the job has failed)
      if: failure()
      run: |
          echo '{"text":":warning: Github Actions: build_navitia_packages_for_dev failed (https://github.com/CanalTP/navitia/actions?query=workflow%3A%22Build+Navitia+Packages+For+Dev%22)"}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}
