name: Publish Docker Compose Images

on:
  workflow_run:
    workflows: ["Build Navitia Packages For Dev Multi Distributions"]
    branches: [publish_docker_compose_job_is_waiting]
    types:
      - completed
      - requested

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get branch name
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        repository: CanalTP/navitia-docker-compose
    - name: install httpie dependency
      run: sudo apt update && sudo apt install -y httpie
    - name: build, create and publish images for branch [ ${{ env.BRANCH_NAME }} ]
      working-directory: builder_from_package
      run: ./build.sh -e push -o ${{secrets.access_token_github}} -t navitia_builder -b ${{ env.BRANCH_NAME }} -r -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}

