name: Publish Docker Compose Images

on:
  push:
    branches:
      - dev
      - release
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: CanalTP/navitia-docker-compose
    - name: install httpie dependency
      run: sudo apt update && sudo apt install -y httpie
    - name: build, create and publish images for branch [ dev ]
      working-directory: builder_from_package
      run: ./build.sh -o ${{secrets.action_secret_key}} -t navitia_builder -b dev -r -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}

